In [36]:
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller
import numpy as np
from itertools import product
from statsmodels.tsa.arima.model import ARIMA
import warnings
from joblib import Parallel, delayed
from tqdm import tqdm

In [37]:
def load_data():
    df = pd.read_csv("../data/data_preprocessed/processed_data.csv")
    df = df.set_index(["Country", "Year"])
    return df

In [38]:
df = load_data()

In [39]:
df

              Capacity  Economic  Ecosystems  Exposure      Food  Governance  \
Country Year
AFG     1995  0.893281  0.496497    0.515884  0.480512  0.665745    0.128090
        1996  0.893892  0.496497    0.516995  0.480512  0.665583    0.128090
        1997  0.894459  0.496497    0.518030  0.480512  0.665420    0.141392
        1998  0.890161  0.496497    0.518156  0.480512  0.657103    0.154694
        1999  0.885896  0.496497    0.518156  0.480512  0.648959    0.143689
...                ...       ...         ...       ...       ...         ...
ZWE     2019  0.597433  0.250663    0.515729  0.516912  0.544129    0.128405
        2020  0.591558  0.260265    0.515480  0.516912  0.571499    0.124162
        2021  0.596365  0.260265    0.515921  0.516912  0.560939    0.131438
        2022  0.583779  0.260265    0.513962  0.516912  0.557942    0.135388
        2023  0.573759  0.260265    0.513962  0.516912  0.559073    0.135101

               Habitat    Health  Infrastructure  Readiness  Sensitivity  \
Country Year
AFG     1995  0.602933  0.748302        0.355586   0.308182     0.419587
        1996  0.604235  0.748302        0.354484   0.308181     0.419307
        1997  0.605583  0.748302        0.353925   0.312614     0.419055
        1998  0.606909  0.748302        0.353710   0.317047     0.418794
        1999  0.608137  0.748302        0.352292   0.313378     0.419433
...                ...       ...             ...        ...          ...
ZWE     2019  0.571407  0.699729        0.320293   0.170180     0.419507
        2020  0.564062  0.699319        0.305472   0.172504     0.432905
        2021  0.556834  0.700294        0.306890   0.177080     0.420585
        2022  0.549853  0.699798        0.299974   0.178652     0.424039
        2023  0.548898  0.699798        0.275926   0.178869     0.424127

                Social  Vulnerability     Water
Country Year
AFG     1995  0.299958       0.612511  0.529692
        1996  0.299954       0.612679  0.528281
        1997  0.299952       0.612837  0.526853
        1998  0.299949       0.611179  0.525424
        1999  0.299947       0.609828  0.525585
...                ...            ...       ...
ZWE     2019  0.131472       0.505822  0.383647
        2020  0.133086       0.507918  0.391679
        2021  0.139537       0.505453  0.391842
        2022  0.140304       0.502217  0.391776
        2023  0.141240       0.498239  0.391776

[5394 rows x 14 columns]

In [40]:
indicators = df.columns
countries = df.index.get_level_values("Country").unique()

In [41]:
results = []

for country in countries:
    for indicator in indicators:

        series = df.loc[country, indicator].dropna()

        try:
            p_value = adfuller(series)[1]
        except ValueError:
            p_value = None

        results.append({
            "Country": country,
            "Indicator": indicator,
            "p_value": p_value
        })

adf_results = pd.DataFrame(results)

/Users/deniz/.pyenv/versions/3.10.6/envs/climate-resilience-dashboard/lib/python3.10/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/Users/deniz/.pyenv/versions/3.10.6/envs/climate-resilience-dashboard/lib/python3.10/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/Users/deniz/.pyenv/versions/3.10.6/envs/climate-resilience-dashboard/lib/python3.10/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/Users/deniz/.pyenv/versions/3.10.6/envs/climate-resilience-dashboard/lib/python3.10/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2

In [42]:
adf_table = adf_results.pivot(
    index="Country",
    columns="Indicator",
    values="p_value"
)

In [43]:
(adf_table > 0.05).sum()

Indicator
Capacity          165
Economic          165
Ecosystems        115
Exposure            0
Food              157
Governance        156
Habitat           151
Health            168
Infrastructure    170
Readiness         166
Sensitivity       151
Social            162
Vulnerability     178
Water             146
dtype: int64

### p > 0.05 → fail to reject the null hypothesis → the series is likely non-stationary.

In [17]:
def fit_arima(series, p, d, q):
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = ARIMA(series, order=(p, d, q)).fit()
        return (p, d, q), model.aic, model
    except:
        return None

results = []

for country in countries:
    for indicator in indicators:
        series = df.loc[country, indicator]

        # Fit all ARIMA combinations in parallel
        results_grid = Parallel(n_jobs=-1)(
            delayed(fit_arima)(series, p, d, q)
            for p, d, q in tqdm(
                product(range(4), range(3), range(4)),
                desc=f"{country} - {indicator}",
                total=48  # 4 × 3 × 4
            )
        )

        # Find best model
        valid_results = [r for r in results_grid if r is not None]

        if not valid_results:
            print(f"Skipping {country} - {indicator}")
            continue

        best_order, best_aic, best_model = min(valid_results, key=lambda x: x[1])

        results.append({
            "Country": country,
            "Indicator": indicator,
            "Order": best_order,
            "AIC": best_aic,
            "BIC": best_model.bic,
        })

# Convert to DataFrame if needed
import pandas as pd
df_results = pd.DataFrame(results)

AFG - Capacity: 100%|██████████| 48/48 [00:01<00:00, 33.39it/s]
AFG - Economic: 100%|██████████| 48/48 [00:00<00:00, 822.06it/s]
AFG - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 533.38it/s]
AFG - Exposure: 100%|██████████| 48/48 [00:00<00:00, 832.11it/s]
AFG - Food: 100%|██████████| 48/48 [00:00<00:00, 527.33it/s]
AFG - Governance: 100%|██████████| 48/48 [00:00<00:00, 829.04it/s]
AFG - Habitat: 100%|██████████| 48/48 [00:00<00:00, 487.47it/s]
AFG - Health: 100%|██████████| 48/48 [00:00<00:00, 835.10it/s]
AFG - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 527.13it/s]
AFG - Readiness: 100%|██████████| 48/48 [00:00<00:00, 799.88it/s]
AFG - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 568.56it/s]
AFG - Social: 100%|██████████| 48/48 [00:00<00:00, 748.27it/s]
AFG - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 806.95it/s]
AFG - Water: 100%|██████████| 48/48 [00:00<00:00, 735.03it/s]
AGO - Capacity: 100%|██████████| 48/48 [00:00<00:00, 466.42it/s]
AGO - Economic: 100%|██████████| 48/48 [00:00<00:00, 842.75it/s]
AGO - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 495.50it/s]
AGO - Exposure: 100%|██████████| 48/48 [00:00<00:00, 800.79it/s]
AGO - Food: 100%|██████████| 48/48 [00:00<00:00, 463.18it/s]
AGO - Governance: 100%|██████████| 48/48 [00:00<00:00, 811.91it/s]
AGO - Habitat: 100%|██████████| 48/48 [00:00<00:00, 490.62it/s]
AGO - Health: 100%|██████████| 48/48 [00:00<00:00, 836.42it/s]
AGO - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 519.34it/s]
AGO - Readiness: 100%|██████████| 48/48 [00:00<00:00, 819.42it/s]
AGO - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 528.56it/s]
AGO - Social: 100%|██████████| 48/48 [00:00<00:00, 822.15it/s]
AGO - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 536.00it/s]
AGO - Water: 100%|██████████| 48/48 [00:00<00:00, 834.07it/s]
ALB - Capacity: 100%|██████████| 48/48 [00:00<00:00, 497.53it/s]
ALB - Economic: 100%|██████████| 48/48 [00:00<00:00, 931.23it/s]
ALB - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 482.03it/s]
ALB - Exposure: 100%|██████████| 48/48 [00:00<00:00, 879.70it/s]
ALB - Food: 100%|██████████| 48/48 [00:00<00:00, 502.47it/s]
ALB - Governance: 100%|██████████| 48/48 [00:00<00:00, 838.50it/s]
ALB - Habitat: 100%|██████████| 48/48 [00:00<00:00, 543.42it/s]
ALB - Health: 100%|██████████| 48/48 [00:00<00:00, 782.39it/s]
ALB - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 865.31it/s]
ALB - Readiness: 100%|██████████| 48/48 [00:00<00:00, 820.77it/s]
ALB - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 467.90it/s]
ALB - Social: 100%|██████████| 48/48 [00:00<00:00, 871.08it/s]
ALB - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 490.95it/s]
ALB - Water: 100%|██████████| 48/48 [00:00<00:00, 807.35it/s]
ARE - Capacity: 100%|██████████| 48/48 [00:00<00:00, 459.65it/s]
ARE - Economic: 100%|██████████| 48/48 [00:00<00:00, 810.73it/s]
ARE - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 448.16it/s]
ARE - Exposure: 100%|██████████| 48/48 [00:00<00:00, 799.24it/s]
ARE - Food: 100%|██████████| 48/48 [00:00<00:00, 513.44it/s]
ARE - Governance: 100%|██████████| 48/48 [00:00<00:00, 950.55it/s]
ARE - Habitat: 100%|██████████| 48/48 [00:00<00:00, 460.10it/s]
ARE - Health: 100%|██████████| 48/48 [00:00<00:00, 796.93it/s]
ARE - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 512.14it/s]
ARE - Readiness: 100%|██████████| 48/48 [00:00<00:00, 748.75it/s]
ARE - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 494.10it/s]
ARE - Social: 100%|██████████| 48/48 [00:00<00:00, 688.71it/s]
ARE - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 494.95it/s]
ARE - Water: 100%|██████████| 48/48 [00:00<00:00, 766.26it/s]
ARG - Capacity: 100%|██████████| 48/48 [00:00<00:00, 514.02it/s]
ARG - Economic: 100%|██████████| 48/48 [00:00<00:00, 892.52it/s]
ARG - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 511.55it/s]
ARG - Exposure: 100%|██████████| 48/48 [00:00<00:00, 855.16it/s]
ARG - Food: 100%|██████████| 48/48 [00:00<00:00, 766.88it/s]
ARG - Governance: 100%|██████████| 48/48 [00:00<00:00, 610.92it/s]
ARG - Habitat: 100%|██████████| 48/48 [00:00<00:00, 473.56it/s]
ARG - Health: 100%|██████████| 48/48 [00:00<00:00, 793.33it/s]
ARG - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 504.20it/s]
ARG - Readiness: 100%|██████████| 48/48 [00:00<00:00, 840.38it/s]
ARG - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 491.11it/s]
ARG - Social: 100%|██████████| 48/48 [00:00<00:00, 803.78it/s]
ARG - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 518.31it/s]
ARG - Water: 100%|██████████| 48/48 [00:00<00:00, 751.89it/s]
ARM - Capacity: 100%|██████████| 48/48 [00:00<00:00, 464.40it/s]
ARM - Economic: 100%|██████████| 48/48 [00:00<00:00, 909.83it/s]
ARM - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 476.90it/s]
ARM - Exposure: 100%|██████████| 48/48 [00:00<00:00, 874.17it/s]
ARM - Food: 100%|██████████| 48/48 [00:00<00:00, 463.78it/s]
ARM - Governance: 100%|██████████| 48/48 [00:00<00:00, 813.82it/s]
ARM - Habitat: 100%|██████████| 48/48 [00:00<00:00, 469.84it/s]
ARM - Health: 100%|██████████| 48/48 [00:00<00:00, 734.82it/s]
ARM - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 375.98it/s]
ARM - Readiness: 100%|██████████| 48/48 [00:00<00:00, 818.06it/s]
ARM - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 459.84it/s]
ARM - Social: 100%|██████████| 48/48 [00:00<00:00, 735.32it/s]
ARM - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 496.69it/s]
ARM - Water: 100%|██████████| 48/48 [00:00<00:00, 723.78it/s]
ATG - Capacity: 100%|██████████| 48/48 [00:00<00:00, 485.96it/s]
ATG - Economic: 100%|██████████| 48/48 [00:00<00:00, 791.26it/s]
ATG - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 526.07it/s]
ATG - Exposure: 100%|██████████| 48/48 [00:00<00:00, 877.03it/s]
ATG - Food: 100%|██████████| 48/48 [00:00<00:00, 502.81it/s]
ATG - Governance: 100%|██████████| 48/48 [00:00<00:00, 851.15it/s]
ATG - Habitat: 100%|██████████| 48/48 [00:00<00:00, 792.08it/s]
ATG - Health: 100%|██████████| 48/48 [00:00<00:00, 776.12it/s]
ATG - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 413.88it/s]
ATG - Readiness: 100%|██████████| 48/48 [00:00<00:00, 816.40it/s]
ATG - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 480.11it/s]
ATG - Social: 100%|██████████| 48/48 [00:00<00:00, 714.40it/s]
ATG - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 438.16it/s]
ATG - Water: 100%|██████████| 48/48 [00:00<00:00, 740.19it/s]
AUS - Capacity: 100%|██████████| 48/48 [00:00<00:00, 457.17it/s]
AUS - Economic: 100%|██████████| 48/48 [00:00<00:00, 839.54it/s]
AUS - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 406.39it/s]
AUS - Exposure: 100%|██████████| 48/48 [00:00<00:00, 804.42it/s]
AUS - Food: 100%|██████████| 48/48 [00:00<00:00, 499.16it/s]
AUS - Governance: 100%|██████████| 48/48 [00:00<00:00, 590.92it/s]
AUS - Habitat: 100%|██████████| 48/48 [00:00<00:00, 434.89it/s]
AUS - Health: 100%|██████████| 48/48 [00:00<00:00, 756.81it/s]
AUS - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 455.73it/s]
AUS - Readiness: 100%|██████████| 48/48 [00:00<00:00, 770.92it/s]
AUS - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 453.71it/s]
AUS - Social: 100%|██████████| 48/48 [00:00<00:00, 701.77it/s]
AUS - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 448.85it/s]
AUS - Water: 100%|██████████| 48/48 [00:00<00:00, 793.85it/s]
AUT - Capacity: 100%|██████████| 48/48 [00:00<00:00, 460.82it/s]
AUT - Economic: 100%|██████████| 48/48 [00:00<00:00, 788.18it/s]
AUT - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 443.87it/s]
AUT - Exposure: 100%|██████████| 48/48 [00:00<00:00, 840.46it/s]
AUT - Food: 100%|██████████| 48/48 [00:00<00:00, 780.23it/s]
AUT - Governance: 100%|██████████| 48/48 [00:00<00:00, 742.84it/s]
AUT - Habitat: 100%|██████████| 48/48 [00:00<00:00, 431.43it/s]
AUT - Health: 100%|██████████| 48/48 [00:00<00:00, 792.09it/s]
AUT - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 424.15it/s]
AUT - Readiness: 100%|██████████| 48/48 [00:00<00:00, 808.54it/s]
AUT - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 416.82it/s]
AUT - Social: 100%|██████████| 48/48 [00:00<00:00, 709.23it/s]
AUT - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 420.60it/s]
AUT - Water: 100%|██████████| 48/48 [00:00<00:00, 847.15it/s]
AZE - Capacity: 100%|██████████| 48/48 [00:00<00:00, 418.75it/s]
AZE - Economic: 100%|██████████| 48/48 [00:00<00:00, 726.26it/s]
AZE - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 412.68it/s]
AZE - Exposure: 100%|██████████| 48/48 [00:00<00:00, 809.45it/s]
AZE - Food: 100%|██████████| 48/48 [00:00<00:00, 396.44it/s]
AZE - Governance: 100%|██████████| 48/48 [00:00<00:00, 776.91it/s]
AZE - Habitat: 100%|██████████| 48/48 [00:00<00:00, 456.50it/s]
AZE - Health: 100%|██████████| 48/48 [00:00<00:00, 707.86it/s]
AZE - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 426.40it/s]
AZE - Readiness: 100%|██████████| 48/48 [00:00<00:00, 750.97it/s]
AZE - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 428.91it/s]
AZE - Social: 100%|██████████| 48/48 [00:00<00:00, 677.97it/s]
AZE - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 441.71it/s]
AZE - Water: 100%|██████████| 48/48 [00:00<00:00, 687.83it/s]
BDI - Capacity: 100%|██████████| 48/48 [00:00<00:00, 454.46it/s]
BDI - Economic: 100%|██████████| 48/48 [00:00<00:00, 842.64it/s]
BDI - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 456.91it/s]
BDI - Exposure: 100%|██████████| 48/48 [00:00<00:00, 801.05it/s]
BDI - Food: 100%|██████████| 48/48 [00:00<00:00, 470.05it/s]
BDI - Governance: 100%|██████████| 48/48 [00:00<00:00, 742.97it/s]
BDI - Habitat: 100%|██████████| 48/48 [00:00<00:00, 729.81it/s]
BDI - Health: 100%|██████████| 48/48 [00:00<00:00, 754.34it/s]
BDI - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 390.24it/s]
BDI - Readiness: 100%|██████████| 48/48 [00:00<00:00, 720.38it/s]
BDI - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 416.67it/s]
BDI - Social: 100%|██████████| 48/48 [00:00<00:00, 768.28it/s]
BDI - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 446.06it/s]
BDI - Water: 100%|██████████| 48/48 [00:00<00:00, 716.80it/s]
BEL - Capacity: 100%|██████████| 48/48 [00:00<00:00, 452.94it/s]
BEL - Economic: 100%|██████████| 48/48 [00:00<00:00, 799.38it/s]
BEL - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 428.86it/s]
BEL - Exposure: 100%|██████████| 48/48 [00:00<00:00, 723.48it/s]
BEL - Food: 100%|██████████| 48/48 [00:00<00:00, 435.07it/s]
BEL - Governance: 100%|██████████| 48/48 [00:00<00:00, 741.87it/s]
BEL - Habitat: 100%|██████████| 48/48 [00:00<00:00, 412.35it/s]
BEL - Health: 100%|██████████| 48/48 [00:00<00:00, 646.14it/s]
BEL - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 448.59it/s]
BEL - Readiness: 100%|██████████| 48/48 [00:00<00:00, 685.32it/s]
BEL - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 492.37it/s]
BEL - Social: 100%|██████████| 48/48 [00:00<00:00, 510.54it/s]
BEL - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 504.14it/s]
BEL - Water: 100%|██████████| 48/48 [00:00<00:00, 727.66it/s]
BEN - Capacity: 100%|██████████| 48/48 [00:00<00:00, 661.55it/s]
BEN - Economic: 100%|██████████| 48/48 [00:00<00:00, 916.70it/s]
BEN - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 426.31it/s]
BEN - Exposure: 100%|██████████| 48/48 [00:00<00:00, 792.52it/s]
BEN - Food: 100%|██████████| 48/48 [00:00<00:00, 420.60it/s]
BEN - Governance: 100%|██████████| 48/48 [00:00<00:00, 775.25it/s]
BEN - Habitat: 100%|██████████| 48/48 [00:00<00:00, 427.41it/s]
BEN - Health: 100%|██████████| 48/48 [00:00<00:00, 853.87it/s]
BEN - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 379.33it/s]
BEN - Readiness: 100%|██████████| 48/48 [00:00<00:00, 774.58it/s]
BEN - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 418.04it/s]
BEN - Social: 100%|██████████| 48/48 [00:00<00:00, 798.27it/s]
BEN - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 431.98it/s]
BEN - Water: 100%|██████████| 48/48 [00:00<00:00, 665.26it/s]
BFA - Capacity: 100%|██████████| 48/48 [00:00<00:00, 428.45it/s]
BFA - Economic: 100%|██████████| 48/48 [00:00<00:00, 793.86it/s]
BFA - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 440.75it/s]
BFA - Exposure: 100%|██████████| 48/48 [00:00<00:00, 787.65it/s]
BFA - Food: 100%|██████████| 48/48 [00:00<00:00, 404.56it/s]
BFA - Governance: 100%|██████████| 48/48 [00:00<00:00, 749.46it/s]
BFA - Habitat: 100%|██████████| 48/48 [00:00<00:00, 374.80it/s]
BFA - Health: 100%|██████████| 48/48 [00:00<00:00, 772.68it/s]
BFA - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 451.39it/s]
BFA - Readiness: 100%|██████████| 48/48 [00:00<00:00, 766.86it/s]
BFA - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 435.97it/s]
BFA - Social: 100%|██████████| 48/48 [00:00<00:00, 678.93it/s]
BFA - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 468.45it/s]
BFA - Water: 100%|██████████| 48/48 [00:00<00:00, 660.19it/s]
BGD - Capacity: 100%|██████████| 48/48 [00:00<00:00, 459.77it/s]
BGD - Economic: 100%|██████████| 48/48 [00:00<00:00, 880.82it/s]
BGD - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 383.94it/s]
BGD - Exposure: 100%|██████████| 48/48 [00:00<00:00, 750.71it/s]
BGD - Food: 100%|██████████| 48/48 [00:00<00:00, 686.42it/s]
BGD - Governance: 100%|██████████| 48/48 [00:00<00:00, 795.25it/s]
BGD - Habitat: 100%|██████████| 48/48 [00:00<00:00, 410.19it/s]
BGD - Health: 100%|██████████| 48/48 [00:00<00:00, 694.38it/s]
BGD - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 458.24it/s]
BGD - Readiness: 100%|██████████| 48/48 [00:00<00:00, 818.75it/s]
BGD - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 413.25it/s]
BGD - Social: 100%|██████████| 48/48 [00:00<00:00, 714.89it/s]
BGD - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 445.76it/s]
BGD - Water: 100%|██████████| 48/48 [00:00<00:00, 735.50it/s]
BGR - Capacity: 100%|██████████| 48/48 [00:00<00:00, 450.59it/s]
BGR - Economic: 100%|██████████| 48/48 [00:00<00:00, 893.68it/s]
BGR - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 404.70it/s]
BGR - Exposure: 100%|██████████| 48/48 [00:00<00:00, 760.85it/s]
BGR - Food: 100%|██████████| 48/48 [00:00<00:00, 433.71it/s]
BGR - Governance: 100%|██████████| 48/48 [00:00<00:00, 651.44it/s]
BGR - Habitat: 100%|██████████| 48/48 [00:00<00:00, 410.40it/s]
BGR - Health: 100%|██████████| 48/48 [00:00<00:00, 716.38it/s]
BGR - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 492.06it/s]
BGR - Readiness: 100%|██████████| 48/48 [00:00<00:00, 666.84it/s]
BGR - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 445.39it/s]
BGR - Social: 100%|██████████| 48/48 [00:00<00:00, 688.51it/s]
BGR - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 390.02it/s]
BGR - Water: 100%|██████████| 48/48 [00:00<00:00, 846.24it/s]
BHR - Capacity: 100%|██████████| 48/48 [00:00<00:00, 810.67it/s]
BHR - Economic: 100%|██████████| 48/48 [00:00<00:00, 718.15it/s]
BHR - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 395.57it/s]
BHR - Exposure: 100%|██████████| 48/48 [00:00<00:00, 722.87it/s]
BHR - Food: 100%|██████████| 48/48 [00:00<00:00, 383.51it/s]
BHR - Governance: 100%|██████████| 48/48 [00:00<00:00, 869.61it/s]
BHR - Habitat: 100%|██████████| 48/48 [00:00<00:00, 409.82it/s]
BHR - Health: 100%|██████████| 48/48 [00:00<00:00, 796.02it/s]
BHR - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 445.10it/s]
BHR - Readiness: 100%|██████████| 48/48 [00:00<00:00, 695.67it/s]
BHR - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 397.46it/s]
BHR - Social: 100%|██████████| 48/48 [00:00<00:00, 621.79it/s]
BHR - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 406.53it/s]
BHR - Water: 100%|██████████| 48/48 [00:00<00:00, 843.02it/s]
BHS - Capacity: 100%|██████████| 48/48 [00:00<00:00, 413.05it/s]
BHS - Economic: 100%|██████████| 48/48 [00:00<00:00, 828.31it/s]
BHS - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 440.44it/s]
BHS - Exposure: 100%|██████████| 48/48 [00:00<00:00, 753.92it/s]
BHS - Food: 100%|██████████| 48/48 [00:00<00:00, 442.34it/s]
BHS - Governance: 100%|██████████| 48/48 [00:00<00:00, 742.91it/s]
BHS - Habitat: 100%|██████████| 48/48 [00:00<00:00, 356.87it/s]
BHS - Health: 100%|██████████| 48/48 [00:00<00:00, 713.33it/s]
BHS - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 416.75it/s]
BHS - Readiness: 100%|██████████| 48/48 [00:00<00:00, 755.06it/s]
BHS - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 458.77it/s]
BHS - Social: 100%|██████████| 48/48 [00:00<00:00, 718.67it/s]
BHS - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 468.21it/s]
BHS - Water: 100%|██████████| 48/48 [00:00<00:00, 743.15it/s]
BIH - Capacity: 100%|██████████| 48/48 [00:00<00:00, 453.74it/s]
BIH - Economic: 100%|██████████| 48/48 [00:00<00:00, 761.71it/s]
BIH - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 466.94it/s]
BIH - Exposure: 100%|██████████| 48/48 [00:00<00:00, 727.11it/s]
BIH - Food: 100%|██████████| 48/48 [00:00<00:00, 411.10it/s]
BIH - Governance: 100%|██████████| 48/48 [00:00<00:00, 667.11it/s]
BIH - Habitat: 100%|██████████| 48/48 [00:00<00:00, 469.70it/s]
BIH - Health: 100%|██████████| 48/48 [00:00<00:00, 462.82it/s]
BIH - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 617.61it/s]
BIH - Readiness: 100%|██████████| 48/48 [00:00<00:00, 646.71it/s]
BIH - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 345.24it/s]
BIH - Social: 100%|██████████| 48/48 [00:00<00:00, 699.91it/s]
BIH - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 404.24it/s]
BIH - Water: 100%|██████████| 48/48 [00:00<00:00, 711.93it/s]
BLR - Capacity: 100%|██████████| 48/48 [00:00<00:00, 380.48it/s]
BLR - Economic: 100%|██████████| 48/48 [00:00<00:00, 820.76it/s]
BLR - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 426.19it/s]
BLR - Exposure: 100%|██████████| 48/48 [00:00<00:00, 769.99it/s]
BLR - Food: 100%|██████████| 48/48 [00:00<00:00, 418.95it/s]
BLR - Governance: 100%|██████████| 48/48 [00:00<00:00, 759.64it/s]
BLR - Habitat: 100%|██████████| 48/48 [00:00<00:00, 399.44it/s]
BLR - Health: 100%|██████████| 48/48 [00:00<00:00, 801.74it/s]
BLR - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 435.40it/s]
BLR - Readiness: 100%|██████████| 48/48 [00:00<00:00, 692.06it/s]
BLR - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 419.36it/s]
BLR - Social: 100%|██████████| 48/48 [00:00<00:00, 781.62it/s]
BLR - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 405.78it/s]
BLR - Water: 100%|██████████| 48/48 [00:00<00:00, 736.57it/s]
BLZ - Capacity: 100%|██████████| 48/48 [00:00<00:00, 451.39it/s]
BLZ - Economic: 100%|██████████| 48/48 [00:00<00:00, 728.73it/s]
BLZ - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 407.45it/s]
BLZ - Exposure: 100%|██████████| 48/48 [00:00<00:00, 750.80it/s]
BLZ - Food: 100%|██████████| 48/48 [00:00<00:00, 448.03it/s]
BLZ - Governance: 100%|██████████| 48/48 [00:00<00:00, 697.40it/s]
BLZ - Habitat: 100%|██████████| 48/48 [00:00<00:00, 391.51it/s]
BLZ - Health: 100%|██████████| 48/48 [00:00<00:00, 738.86it/s]
BLZ - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 427.51it/s]
BLZ - Readiness: 100%|██████████| 48/48 [00:00<00:00, 751.56it/s]
BLZ - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 627.75it/s]
BLZ - Social: 100%|██████████| 48/48 [00:00<00:00, 525.15it/s]
BLZ - Vulnerability: 100%|██████████| 48/48 [00:00<00:00, 365.21it/s]
BLZ - Water: 100%|██████████| 48/48 [00:00<00:00, 771.63it/s]
BOL - Capacity: 100%|██████████| 48/48 [00:00<00:00, 401.25it/s]
BOL - Economic: 100%|██████████| 48/48 [00:00<00:00, 717.28it/s]
BOL - Ecosystems: 100%|██████████| 48/48 [00:00<00:00, 370.94it/s]
BOL - Exposure: 100%|██████████| 48/48 [00:00<00:00, 710.28it/s]
BOL - Food: 100%|██████████| 48/48 [00:00<00:00, 391.30it/s]
BOL - Governance: 100%|██████████| 48/48 [00:00<00:00, 752.66it/s]
BOL - Habitat: 100%|██████████| 48/48 [00:00<00:00, 327.69it/s]
BOL - Health: 100%|██████████| 48/48 [00:00<00:00, 691.36it/s]
BOL - Infrastructure: 100%|██████████| 48/48 [00:00<00:00, 379.77it/s]
BOL - Readiness: 100%|██████████| 48/48 [00:00<00:00, 676.04it/s]
BOL - Sensitivity: 100%|██████████| 48/48 [00:00<00:00, 424.89it/s]

In [22]:
results_df = pd.DataFrame(results)

In [23]:
results_df

     Country      Indicator      Order         AIC         BIC
0        AFG       Capacity  (3, 0, 1) -167.254275 -159.050500
1        AFG       Economic  (0, 1, 1) -103.036247 -100.371838
2        AFG     Ecosystems  (1, 0, 0) -270.389178 -266.287291
3        AFG       Exposure  (0, 1, 0) -689.299058 -687.966853
4        AFG           Food  (1, 0, 2) -177.312727 -170.476247
...      ...            ...        ...         ...         ...
2599     ZWE      Readiness  (2, 0, 0) -186.989915 -181.520732
2600     ZWE    Sensitivity  (1, 0, 0) -183.861247 -179.759360
2601     ZWE         Social  (2, 0, 2) -230.876638 -222.672863
2602     ZWE  Vulnerability  (1, 0, 0) -232.783278 -228.681391
2603     ZWE          Water  (1, 0, 2) -272.157315 -265.320836

[2604 rows x 5 columns]

In [12]:
results = pd.read_csv("model_results_all_sectors.csv")

In [26]:
order_df = pd.DataFrame(results.groupby(['Indicator','Order']).size())

In [31]:
order_df.head()

                      0
Indicator Order
Capacity  (0, 0, 1)   4
          (0, 0, 3)   2
          (0, 1, 0)  12
          (0, 1, 1)   4
          (0, 1, 2)   4

In [32]:
order_df = order_df.reset_index()
order_df.columns = ['Indicator', 'Order', 'Count']

In [35]:
# Smallest (p,d,q) for each indicator
smallest = (
    order_df.groupby('Indicator')['Order']
    .min()
    .rename('Smallest_Order')
)

# Most frequent order for each indicator
most_frequent = (
    order_df.loc[
        order_df.groupby('Indicator')['Count'].idxmax(),
        ['Indicator', 'Order', 'Count']
    ]
    .rename(columns={
        'Order': 'Most_Frequent_Order',
        'Count': 'Frequency'
    })
    .set_index('Indicator')
)

summary = (
    smallest.to_frame()
    .join(most_frequent)
    .reset_index()
)

summary

         Indicator Smallest_Order Most_Frequent_Order  Frequency
0         Capacity      (0, 0, 1)           (1, 0, 0)         42
1         Economic      (0, 0, 0)           (1, 0, 0)         56
2       Ecosystems      (0, 0, 0)           (2, 0, 0)         58
3         Exposure      (0, 1, 0)           (0, 1, 0)        186
4             Food      (0, 0, 0)           (1, 0, 0)         79
5       Governance      (0, 0, 1)           (1, 0, 0)         60
6          Habitat      (0, 0, 1)           (1, 0, 1)         53
7           Health      (0, 0, 1)           (1, 0, 0)         63
8   Infrastructure      (0, 0, 0)           (1, 0, 0)         36
9        Readiness      (0, 0, 1)           (1, 0, 0)         52
10     Sensitivity      (0, 0, 0)           (1, 0, 0)         72
11          Social      (0, 1, 0)           (2, 0, 1)         32
12   Vulnerability      (0, 0, 1)           (1, 0, 0)         85
13           Water      (0, 0, 0)           (2, 0, 0)         58

In [52]:
summary['Smallest_Order'].unique()

array(['(0, 0, 1)', '(0, 0, 0)', '(0, 1, 0)'], dtype=object)

In [53]:
summary['Most_Frequent_Order'].unique()

array(['(1, 0, 0)', '(2, 0, 0)', '(0, 1, 0)', '(1, 0, 1)', '(2, 0, 1)'],
      dtype=object)

In [54]:
grid = [(0, 0, 1), (0, 0, 0), (0, 1, 0), (1, 0, 0), (2, 0, 0), (1, 0, 0), (2, 0, 1)]

## Running Grid Search based on results of previous run.

In [55]:
def fit_arima(series, p, d, q):
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = ARIMA(series, order=(p, d, q)).fit()

            # Calculate MSE from residuals
            mse = np.mean(model.resid ** 2)

            return (p, d, q), model.aic, model.bic, mse, model
    except:
        return None

# Your grid search results from yesterday
grid = [(0, 0, 1), (0, 0, 0), (0, 1, 0), (1, 0, 0), (2, 0, 0), (1, 0, 0), (2, 0, 1)]

results = []

for country in countries:
    for indicator in indicators:
        series = df.loc[country, indicator]

        # Fit only the grid combinations
        results_grid = Parallel(n_jobs=-1)(
            delayed(fit_arima)(series, p, d, q)
            for p, d, q in tqdm(
                grid,
                desc=f"{country} - {indicator}",
                total=len(grid)
            )
        )

        # Find best model by AIC
        valid_results = [r for r in results_grid if r is not None]

        if not valid_results:
            print(f"Skipping {country} - {indicator}")
            continue

        best_order, best_aic, best_bic, best_mse, best_model = min(
            valid_results, key=lambda x: x[1]  # Still using AIC as criterion
        )

        results.append({
            "Country": country,
            "Indicator": indicator,
            "Order": best_order,
            "AIC": best_aic,
            "BIC": best_bic,
            "MSE": best_mse,
        })

# Convert to DataFrame
df_results = pd.DataFrame(results)

AFG - Capacity: 100%|██████████| 7/7 [00:00<00:00, 943.15it/s]
AFG - Economic: 100%|██████████| 7/7 [00:00<00:00, 6698.64it/s]
AFG - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 17676.18it/s]
AFG - Exposure: 100%|██████████| 7/7 [00:00<00:00, 14798.45it/s]
AFG - Food: 100%|██████████| 7/7 [00:00<00:00, 15870.34it/s]
AFG - Governance: 100%|██████████| 7/7 [00:00<00:00, 16587.64it/s]
AFG - Habitat: 100%|██████████| 7/7 [00:00<00:00, 20896.89it/s]
AFG - Health: 100%|██████████| 7/7 [00:00<00:00, 17445.11it/s]
AFG - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 22429.43it/s]
AFG - Readiness: 100%|██████████| 7/7 [00:00<00:00, 13412.58it/s]
AFG - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 14987.30it/s]
AFG - Social: 100%|██████████| 7/7 [00:00<00:00, 17414.07it/s]
AFG - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 17240.24it/s]
AFG - Water: 100%|██████████| 7/7 [00:00<00:00, 15550.92it/s]
AGO - Capacity: 100%|██████████| 7/7 [00:00<00:00, 17291.01it/s]
AGO - Economic: 100%|██████████| 7/7 [00:00<00:00, 19771.13it/s]
AGO - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 18712.64it/s]
AGO - Exposure: 100%|██████████| 7/7 [00:00<00:00, 23734.95it/s]
AGO - Food: 100%|██████████| 7/7 [00:00<00:00, 14197.35it/s]
AGO - Governance: 100%|██████████| 7/7 [00:00<00:00, 19127.12it/s]
AGO - Habitat: 100%|██████████| 7/7 [00:00<00:00, 21076.90it/s]
AGO - Health: 100%|██████████| 7/7 [00:00<00:00, 21198.65it/s]
AGO - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 15982.65it/s]
AGO - Readiness: 100%|██████████| 7/7 [00:00<00:00, 12456.57it/s]
AGO - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19704.78it/s]
AGO - Social: 100%|██████████| 7/7 [00:00<00:00, 17372.86it/s]
AGO - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 18724.57it/s]
AGO - Water: 100%|██████████| 7/7 [00:00<00:00, 22498.18it/s]
ALB - Capacity: 100%|██████████| 7/7 [00:00<00:00, 20474.29it/s]
ALB - Economic: 100%|██████████| 7/7 [00:00<00:00, 21137.60it/s]
ALB - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
ALB - Exposure: 100%|██████████| 7/7 [00:00<00:00, 17280.83it/s]
ALB - Food: 100%|██████████| 7/7 [00:00<00:00, 20403.15it/s]
ALB - Governance: 100%|██████████| 7/7 [00:00<00:00, 17465.87it/s]
ALB - Habitat: 100%|██████████| 7/7 [00:00<00:00, 24045.97it/s]
ALB - Health: 100%|██████████| 7/7 [00:00<00:00, 12218.11it/s]
ALB - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 17772.47it/s]
ALB - Readiness: 100%|██████████| 7/7 [00:00<00:00, 20346.59it/s]
ALB - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 15518.04it/s]
ALB - Social: 100%|██████████| 7/7 [00:00<00:00, 20000.09it/s]
ALB - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 13255.14it/s]
ALB - Water: 100%|██████████| 7/7 [00:00<00:00, 17240.24it/s]
ARE - Capacity: 100%|██████████| 7/7 [00:00<00:00, 20632.56it/s]
ARE - Economic: 100%|██████████| 7/7 [00:00<00:00, 11905.97it/s]
ARE - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 16951.58it/s]
ARE - Exposure: 100%|██████████| 7/7 [00:00<00:00, 15315.66it/s]
ARE - Food: 100%|██████████| 7/7 [00:00<00:00, 18001.30it/s]
ARE - Governance: 100%|██████████| 7/7 [00:00<00:00, 13592.65it/s]
ARE - Habitat: 100%|██████████| 7/7 [00:00<00:00, 20896.89it/s]
ARE - Health: 100%|██████████| 7/7 [00:00<00:00, 15947.92it/s]
ARE - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 20837.56it/s]
ARE - Readiness: 100%|██████████| 7/7 [00:00<00:00, 20911.77it/s]
ARE - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 15518.04it/s]
ARE - Social: 100%|██████████| 7/7 [00:00<00:00, 17858.96it/s]
ARE - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 23027.55it/s]
ARE - Water: 100%|██████████| 7/7 [00:00<00:00, 18179.65it/s]
ARG - Capacity: 100%|██████████| 7/7 [00:00<00:00, 21152.83it/s]
ARG - Economic: 100%|██████████| 7/7 [00:00<00:00, 14108.66it/s]
ARG - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 20109.68it/s]
ARG - Exposure: 100%|██████████| 7/7 [00:00<00:00, 17040.12it/s]
ARG - Food: 100%|██████████| 7/7 [00:00<00:00, 16356.62it/s]
ARG - Governance: 100%|██████████| 7/7 [00:00<00:00, 13862.19it/s]
ARG - Habitat: 100%|██████████| 7/7 [00:00<00:00, 18179.65it/s]
ARG - Health: 100%|██████████| 7/7 [00:00<00:00, 17815.61it/s]
ARG - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 14287.17it/s]
ARG - Readiness: 100%|██████████| 7/7 [00:00<00:00, 19189.63it/s]
ARG - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19392.42it/s]
ARG - Social: 100%|██████████| 7/7 [00:00<00:00, 17946.29it/s]
ARG - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 15692.21it/s]
ARG - Water: 100%|██████████| 7/7 [00:00<00:00, 19015.63it/s]
ARM - Capacity: 100%|██████████| 7/7 [00:00<00:00, 18820.59it/s]
ARM - Economic: 100%|██████████| 7/7 [00:00<00:00, 14315.03it/s]
ARM - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 14828.35it/s]
ARM - Exposure: 100%|██████████| 7/7 [00:00<00:00, 14108.66it/s]
ARM - Food: 100%|██████████| 7/7 [00:00<00:00, 18101.19it/s]
ARM - Governance: 100%|██████████| 7/7 [00:00<00:00, 19718.02it/s]
ARM - Habitat: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
ARM - Health: 100%|██████████| 7/7 [00:00<00:00, 21415.12it/s]
ARM - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 20837.56it/s]
ARM - Readiness: 100%|██████████| 7/7 [00:00<00:00, 13947.80it/s]
ARM - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 15252.01it/s]
ARM - Social: 100%|██████████| 7/7 [00:00<00:00, 13183.71it/s]
ARM - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 20589.15it/s]
ARM - Water: 100%|██████████| 7/7 [00:00<00:00, 25420.02it/s]
ATG - Capacity: 100%|██████████| 7/7 [00:00<00:00, 22293.19it/s]
ATG - Economic: 100%|██████████| 7/7 [00:00<00:00, 13207.43it/s]
ATG - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 18523.74it/s]
ATG - Exposure: 100%|██████████| 7/7 [00:00<00:00, 19392.42it/s]
ATG - Food: 100%|██████████| 7/7 [00:00<00:00, 17858.96it/s]
ATG - Governance: 100%|██████████| 7/7 [00:00<00:00, 20054.73it/s]
ATG - Habitat: 100%|██████████| 7/7 [00:00<00:00, 17291.01it/s]
ATG - Health: 100%|██████████| 7/7 [00:00<00:00, 18090.04it/s]
ATG - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 15056.48it/s]
ATG - Readiness: 100%|██████████| 7/7 [00:00<00:00, 17030.24it/s]
ATG - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 18808.54it/s]
ATG - Social: 100%|██████████| 7/7 [00:00<00:00, 13643.18it/s]
ATG - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 19482.50it/s]
ATG - Water: 100%|██████████| 7/7 [00:00<00:00, 17362.58it/s]
AUS - Capacity: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
AUS - Economic: 100%|██████████| 7/7 [00:00<00:00, 14498.83it/s]
AUS - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 21477.78it/s]
AUS - Exposure: 100%|██████████| 7/7 [00:00<00:00, 17040.12it/s]
AUS - Food: 100%|██████████| 7/7 [00:00<00:00, 19077.41it/s]
AUS - Governance: 100%|██████████| 7/7 [00:00<00:00, 19456.68it/s]
AUS - Habitat: 100%|██████████| 7/7 [00:00<00:00, 14336.00it/s]
AUS - Health: 100%|██████████| 7/7 [00:00<00:00, 11041.79it/s]
AUS - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 17455.49it/s]
AUS - Readiness: 100%|██████████| 7/7 [00:00<00:00, 19341.32it/s]
AUS - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 21016.56it/s]
AUS - Social: 100%|██████████| 7/7 [00:00<00:00, 13136.52it/s]
AUS - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 17291.01it/s]
AUS - Water: 100%|██████████| 7/7 [00:00<00:00, 15347.69it/s]
AUT - Capacity: 100%|██████████| 7/7 [00:00<00:00, 13430.98it/s]
AUT - Economic: 100%|██████████| 7/7 [00:00<00:00, 17403.75it/s]
AUT - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 19341.32it/s]
AUT - Exposure: 100%|██████████| 7/7 [00:00<00:00, 16275.02it/s]
AUT - Food: 100%|██████████| 7/7 [00:00<00:00, 21213.97it/s]
AUT - Governance: 100%|██████████| 7/7 [00:00<00:00, 19290.49it/s]
AUT - Habitat: 100%|██████████| 7/7 [00:00<00:00, 16131.94it/s]
AUT - Health: 100%|██████████| 7/7 [00:00<00:00, 14926.35it/s]
AUT - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 15734.26it/s]
AUT - Readiness: 100%|██████████| 7/7 [00:00<00:00, 15518.04it/s]
AUT - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 20346.59it/s]
AUT - Social: 100%|██████████| 7/7 [00:00<00:00, 19612.64it/s]
AUT - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 22009.09it/s]
AUT - Water: 100%|██████████| 7/7 [00:00<00:00, 21213.97it/s]
AZE - Capacity: 100%|██████████| 7/7 [00:00<00:00, 18327.17it/s]
AZE - Economic: 100%|██████████| 7/7 [00:00<00:00, 12638.88it/s]
AZE - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 18179.65it/s]
AZE - Exposure: 100%|██████████| 7/7 [00:00<00:00, 16356.62it/s]
AZE - Food: 100%|██████████| 7/7 [00:00<00:00, 19392.42it/s]
AZE - Governance: 100%|██████████| 7/7 [00:00<00:00, 14315.03it/s]
AZE - Habitat: 100%|██████████| 7/7 [00:00<00:00, 14287.17it/s]
AZE - Health: 100%|██████████| 7/7 [00:00<00:00, 19065.02it/s]
AZE - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 18373.05it/s]
AZE - Readiness: 100%|██████████| 7/7 [00:00<00:00, 11964.19it/s]
AZE - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 17362.58it/s]
AZE - Social: 100%|██████████| 7/7 [00:00<00:00, 14142.64it/s]
AZE - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 20123.46it/s]
AZE - Water: 100%|██████████| 7/7 [00:00<00:00, 18465.49it/s]
BDI - Capacity: 100%|██████████| 7/7 [00:00<00:00, 19443.79it/s]
BDI - Economic: 100%|██████████| 7/7 [00:00<00:00, 16738.96it/s]
BDI - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 18134.73it/s]
BDI - Exposure: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
BDI - Food: 100%|██████████| 7/7 [00:00<00:00, 21415.12it/s]
BDI - Governance: 100%|██████████| 7/7 [00:00<00:00, 18772.46it/s]
BDI - Habitat: 100%|██████████| 7/7 [00:00<00:00, 17676.18it/s]
BDI - Health: 100%|██████████| 7/7 [00:00<00:00, 19665.19it/s]
BDI - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 12699.02it/s]
BDI - Readiness: 100%|██████████| 7/7 [00:00<00:00, 18384.55it/s]
BDI - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 14463.12it/s]
BDI - Social: 100%|██████████| 7/7 [00:00<00:00, 22075.28it/s]
BDI - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 16625.21it/s]
BDI - Water: 100%|██████████| 7/7 [00:00<00:00, 17676.18it/s]
BEL - Capacity: 100%|██████████| 7/7 [00:00<00:00, 18676.93it/s]
BEL - Economic: 100%|██████████| 7/7 [00:00<00:00, 21152.83it/s]
BEL - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 19824.53it/s]
BEL - Exposure: 100%|██████████| 7/7 [00:00<00:00, 21352.82it/s]
BEL - Food: 100%|██████████| 7/7 [00:00<00:00, 19027.95it/s]
BEL - Governance: 100%|██████████| 7/7 [00:00<00:00, 10653.17it/s]
BEL - Habitat: 100%|██████████| 7/7 [00:00<00:00, 21076.90it/s]
BEL - Health: 100%|██████████| 7/7 [00:00<00:00, 21667.99it/s]
BEL - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 18523.74it/s]
BEL - Readiness: 100%|██████████| 7/7 [00:00<00:00, 22812.84it/s]
BEL - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 18978.75it/s]
BEL - Social: 100%|██████████| 7/7 [00:00<00:00, 13031.57it/s]
BEL - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 19277.83it/s]
BEL - Water: 100%|██████████| 7/7 [00:00<00:00, 15118.50it/s]
BEN - Capacity: 100%|██████████| 7/7 [00:00<00:00, 19652.03it/s]
BEN - Economic: 100%|██████████| 7/7 [00:00<00:00, 17990.27it/s]
BEN - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 19560.38it/s]
BEN - Exposure: 100%|██████████| 7/7 [00:00<00:00, 16625.21it/s]
BEN - Food: 100%|██████████| 7/7 [00:00<00:00, 12916.91it/s]
BEN - Governance: 100%|██████████| 7/7 [00:00<00:00, 14427.58it/s]
BEN - Habitat: 100%|██████████| 7/7 [00:00<00:00, 18978.75it/s]
BEN - Health: 100%|██████████| 7/7 [00:00<00:00, 14001.01it/s]
BEN - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 15126.29it/s]
BEN - Readiness: 100%|██████████| 7/7 [00:00<00:00, 13213.38it/s]
BEN - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 17507.53it/s]
BEN - Social: 100%|██████████| 7/7 [00:00<00:00, 15526.24it/s]
BEN - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 17321.61it/s]
BEN - Water: 100%|██████████| 7/7 [00:00<00:00, 21076.90it/s]
BFA - Capacity: 100%|██████████| 7/7 [00:00<00:00, 17676.18it/s]
BFA - Economic: 100%|██████████| 7/7 [00:00<00:00, 18917.61it/s]
BFA - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 18373.05it/s]
BFA - Exposure: 100%|██████████| 7/7 [00:00<00:00, 13967.71it/s]
BFA - Food: 100%|██████████| 7/7 [00:00<00:00, 20220.47it/s]
BFA - Governance: 100%|██████████| 7/7 [00:00<00:00, 14956.76it/s]
BFA - Habitat: 100%|██████████| 7/7 [00:00<00:00, 22654.42it/s]
BFA - Health: 100%|██████████| 7/7 [00:00<00:00, 21337.30it/s]
BFA - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 17761.72it/s]
BFA - Readiness: 100%|██████████| 7/7 [00:00<00:00, 20248.36it/s]
BFA - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19771.13it/s]
BFA - Social: 100%|██████████| 7/7 [00:00<00:00, 16017.53it/s]
BFA - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 19456.68it/s]
BFA - Water: 100%|██████████| 7/7 [00:00<00:00, 16710.37it/s]
BGD - Capacity: 100%|██████████| 7/7 [00:00<00:00, 14163.11it/s]
BGD - Economic: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
BGD - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 19015.63it/s]
BGD - Exposure: 100%|██████████| 7/7 [00:00<00:00, 21796.68it/s]
BGD - Food: 100%|██████████| 7/7 [00:00<00:00, 12865.96it/s]
BGD - Governance: 100%|██████████| 7/7 [00:00<00:00, 18477.11it/s]
BGD - Habitat: 100%|██████████| 7/7 [00:00<00:00, 15844.65it/s]
BGD - Health: 100%|██████████| 7/7 [00:00<00:00, 15592.21it/s]
BGD - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 17507.53it/s]
BGD - Readiness: 100%|██████████| 7/7 [00:00<00:00, 20220.47it/s]
BGD - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19986.47it/s]
BGD - Social: 100%|██████████| 7/7 [00:00<00:00, 18453.88it/s]
BGD - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 14491.67it/s]
BGD - Water: 100%|██████████| 7/7 [00:00<00:00, 19392.42it/s]
BGR - Capacity: 100%|██████████| 7/7 [00:00<00:00, 15283.77it/s]
BGR - Economic: 100%|██████████| 7/7 [00:00<00:00, 20360.70it/s]
BGR - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 19945.74it/s]
BGR - Exposure: 100%|██████████| 7/7 [00:00<00:00, 12704.51it/s]
BGR - Food: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
BGR - Governance: 100%|██████████| 7/7 [00:00<00:00, 18929.81it/s]
BGR - Habitat: 100%|██████████| 7/7 [00:00<00:00, 17902.52it/s]
BGR - Health: 100%|██████████| 7/7 [00:00<00:00, 20178.78it/s]
BGR - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 14498.83it/s]
BGR - Readiness: 100%|██████████| 7/7 [00:00<00:00, 16625.21it/s]
BGR - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 17455.49it/s]
BGR - Social: 100%|██████████| 7/7 [00:00<00:00, 20403.15it/s]
BGR - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 18820.59it/s]
BGR - Water: 100%|██████████| 7/7 [00:00<00:00, 18090.04it/s]
BHR - Capacity: 100%|██████████| 7/7 [00:00<00:00, 19392.42it/s]
BHR - Economic: 100%|██████████| 7/7 [00:00<00:00, 16990.81it/s]
BHR - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 20956.55it/s]
BHR - Exposure: 100%|██████████| 7/7 [00:00<00:00, 16738.96it/s]
BHR - Food: 100%|██████████| 7/7 [00:00<00:00, 16248.00it/s]
BHR - Governance: 100%|██████████| 7/7 [00:00<00:00, 16873.64it/s]
BHR - Habitat: 100%|██████████| 7/7 [00:00<00:00, 17321.61it/s]
BHR - Health: 100%|██████████| 7/7 [00:00<00:00, 19652.03it/s]
BHR - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 22498.18it/s]
BHR - Readiness: 100%|██████████| 7/7 [00:00<00:00, 12843.45it/s]
BHR - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 15734.26it/s]
BHR - Social: 100%|██████████| 7/7 [00:00<00:00, 20290.34it/s]
BHR - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 13668.59it/s]
BHR - Water: 100%|██████████| 7/7 [00:00<00:00, 18134.73it/s]
BHS - Capacity: 100%|██████████| 7/7 [00:00<00:00, 14169.95it/s]
BHS - Economic: 100%|██████████| 7/7 [00:00<00:00, 15126.29it/s]
BHS - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 21076.90it/s]
BHS - Exposure: 100%|██████████| 7/7 [00:00<00:00, 14224.87it/s]
BHS - Food: 100%|██████████| 7/7 [00:00<00:00, 16347.51it/s]
BHS - Governance: 100%|██████████| 7/7 [00:00<00:00, 17990.27it/s]
BHS - Habitat: 100%|██████████| 7/7 [00:00<00:00, 19945.74it/s]
BHS - Health: 100%|██████████| 7/7 [00:00<00:00, 18419.15it/s]
BHS - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 19027.95it/s]
BHS - Readiness: 100%|██████████| 7/7 [00:00<00:00, 17676.18it/s]
BHS - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19027.95it/s]
BHS - Social: 100%|██████████| 7/7 [00:00<00:00, 21275.46it/s]
BHS - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 17815.61it/s]
BHS - Water: 100%|██████████| 7/7 [00:00<00:00, 20000.09it/s]
BIH - Capacity: 100%|██████████| 7/7 [00:00<00:00, 13333.39it/s]
BIH - Economic: 100%|██████████| 7/7 [00:00<00:00, 14054.63it/s]
BIH - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 17990.27it/s]
BIH - Exposure: 100%|██████████| 7/7 [00:00<00:00, 18582.36it/s]
BIH - Food: 100%|██████████| 7/7 [00:00<00:00, 20346.59it/s]
BIH - Governance: 100%|██████████| 7/7 [00:00<00:00, 19015.63it/s]
BIH - Habitat: 100%|██████████| 7/7 [00:00<00:00, 17331.83it/s]
BIH - Health: 100%|██████████| 7/7 [00:00<00:00, 18820.59it/s]
BIH - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 13974.36it/s]
BIH - Readiness: 100%|██████████| 7/7 [00:00<00:00, 20403.15it/s]
BIH - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 16503.73it/s]
BIH - Social: 100%|██████████| 7/7 [00:00<00:00, 20719.92it/s]
BIH - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 20517.21it/s]
BIH - Water: 100%|██████████| 7/7 [00:00<00:00, 19065.02it/s]
BLR - Capacity: 100%|██████████| 7/7 [00:00<00:00, 16475.94it/s]
BLR - Economic: 100%|██████████| 7/7 [00:00<00:00, 18327.17it/s]
BLR - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 18966.49it/s]
BLR - Exposure: 100%|██████████| 7/7 [00:00<00:00, 20882.03it/s]
BLR - Food: 100%|██████████| 7/7 [00:00<00:00, 16710.37it/s]
BLR - Governance: 100%|██████████| 7/7 [00:00<00:00, 21076.90it/s]
BLR - Habitat: 100%|██████████| 7/7 [00:00<00:00, 19824.53it/s]
BLR - Health: 100%|██████████| 7/7 [00:00<00:00, 20000.09it/s]
BLR - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 17633.71it/s]
BLR - Readiness: 100%|██████████| 7/7 [00:00<00:00, 21275.46it/s]
BLR - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19177.09it/s]
BLR - Social: 100%|██████████| 7/7 [00:00<00:00, 19227.33it/s]
BLR - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 19239.93it/s]
BLR - Water: 100%|██████████| 7/7 [00:00<00:00, 19771.13it/s]
BLZ - Capacity: 100%|██████████| 7/7 [00:00<00:00, 17455.49it/s]
BLZ - Economic: 100%|██████████| 7/7 [00:00<00:00, 17750.98it/s]
BLZ - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 20234.41it/s]
BLZ - Exposure: 100%|██████████| 7/7 [00:00<00:00, 15181.04it/s]
BLZ - Food: 100%|██████████| 7/7 [00:00<00:00, 16615.81it/s]
BLZ - Governance: 100%|██████████| 7/7 [00:00<00:00, 13505.12it/s]
BLZ - Habitat: 100%|██████████| 7/7 [00:00<00:00, 13751.82it/s]
BLZ - Health: 100%|██████████| 7/7 [00:00<00:00, 21092.05it/s]
BLZ - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 19560.38it/s]
BLZ - Readiness: 100%|██████████| 7/7 [00:00<00:00, 19443.79it/s]
BLZ - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 10327.16it/s]
BLZ - Social: 100%|██████████| 7/7 [00:00<00:00, 18724.57it/s]
BLZ - Vulnerability: 100%|██████████| 7/7 [00:00<00:00, 20109.68it/s]
BLZ - Water: 100%|██████████| 7/7 [00:00<00:00, 14498.83it/s]
BOL - Capacity: 100%|██████████| 7/7 [00:00<00:00, 11231.88it/s]
BOL - Economic: 100%|██████████| 7/7 [00:00<00:00, 12274.30it/s]
BOL - Ecosystems: 100%|██████████| 7/7 [00:00<00:00, 14463.12it/s]
BOL - Exposure: 100%|██████████| 7/7 [00:00<00:00, 11905.97it/s]
BOL - Food: 100%|██████████| 7/7 [00:00<00:00, 14350.01it/s]
BOL - Governance: 100%|██████████| 7/7 [00:00<00:00, 18384.55it/s]
BOL - Habitat: 100%|██████████| 7/7 [00:00<00:00, 21275.46it/s]
BOL - Health: 100%|██████████| 7/7 [00:00<00:00, 18868.98it/s]
BOL - Infrastructure: 100%|██████████| 7/7 [00:00<00:00, 17079.77it/s]
BOL - Readiness: 100%|██████████| 7/7 [00:00<00:00, 14926.35it/s]
BOL - Sensitivity: 100%|██████████| 7/7 [00:00<00:00, 19945.74it/s]

In [56]:
df_results

     Country      Indicator      Order         AIC         BIC       MSE
0        AFG       Capacity  (0, 1, 0) -159.674542 -158.342338  0.027691
1        AFG       Economic  (0, 1, 0) -101.432891 -100.100687  0.009906
2        AFG     Ecosystems  (1, 0, 0) -270.389178 -266.287291  0.000004
3        AFG       Exposure  (0, 1, 0) -689.299058 -687.966853  0.007962
4        AFG           Food  (1, 0, 0) -176.504170 -172.402282  0.000170
...      ...            ...        ...         ...         ...       ...
2599     ZWE      Readiness  (2, 0, 0) -186.989915 -181.520732  0.000219
2600     ZWE    Sensitivity  (1, 0, 0) -183.861247 -179.759360  0.000098
2601     ZWE         Social  (1, 0, 0) -227.030455 -222.928567  0.000039
2602     ZWE  Vulnerability  (1, 0, 0) -232.783278 -228.681391  0.000015
2603     ZWE          Water  (2, 0, 0) -271.978785 -266.509602  0.000009

[2604 rows x 6 columns]