# EXPLORATORY DATA ANALYSIS OF RAW FILES

In [1]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
DATA_DIR = Path("../raw_data")

readiness = pd.read_csv(DATA_DIR / "readiness" / "readiness.csv")
economic = pd.read_csv(DATA_DIR / "readiness" / "sectors" / "economic.csv")
governance = pd.read_csv(DATA_DIR / "readiness" / "sectors" / "governance.csv")
social = pd.read_csv(DATA_DIR / "readiness" / "sectors" / "social.csv")
vulnerability = pd.read_csv(DATA_DIR / "vulnerability" / "vulnerability.csv")
capacity = pd.read_csv(DATA_DIR / "vulnerability" / "capacity.csv")
exposure = pd.read_csv(DATA_DIR / "vulnerability" / "exposure.csv")
sensitivity = pd.read_csv(DATA_DIR / "vulnerability" / "sensitivity.csv")
ecosystem = pd.read_csv(DATA_DIR / "vulnerability" / "sectors" / "ecosystems.csv")
food = pd.read_csv(DATA_DIR / "vulnerability" / "sectors" / "food.csv")
habitat = pd.read_csv(DATA_DIR / "vulnerability" / "sectors" / "habitat.csv")
health = pd.read_csv(DATA_DIR / "vulnerability" / "sectors" / "health.csv")
infrastructure = pd.read_csv(DATA_DIR / "vulnerability" / "sectors" / "infrastructure.csv")
water = pd.read_csv(DATA_DIR / "vulnerability" / "sectors" / "water.csv")

datasets = {
    "readiness": readiness,
    "economic": economic,
    "governance": governance,
    "social": social,
    "vulnerability": vulnerability,
    "capacity": capacity,
    "exposure": exposure,
    "sensitivity": sensitivity,
    "ecosystem": ecosystem,
    "food": food,
    "habitat": habitat,
    "health": health,
    "infrastructure": infrastructure,
    "water": water
}

In [4]:
for df in datasets.values():
    df.set_index("ISO3", inplace=True)

In [5]:
for name, df in datasets.items():
    print(f"{name:15} {df.shape}")

readiness       (192, 30)
economic        (192, 30)
governance      (192, 30)
social          (192, 30)
vulnerability   (192, 30)
capacity        (192, 30)
exposure        (192, 30)
sensitivity     (192, 30)
ecosystem       (192, 30)
food            (192, 30)
habitat         (192, 30)
health          (192, 30)
infrastructure  (192, 30)
water           (192, 30)

## READINESS

### READINESS INDEX
*Average of 3 Readiness Sectors: Economic, Governance, Social*

In [6]:
readiness.shape

(192, 30)

In [7]:
readiness.head()

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
AFG,Afghanistan,0.309691,0.309690,0.311388,0.313085,0.311566,0.310048,0.316235,0.322440,0.326073,...,0.245383,0.244341,0.255508,0.245953,0.240704,0.248401,0.236749,0.246106,0.249550,0.251374
ALB,Albania,0.332968,0.333487,0.329979,0.326026,0.327192,0.328102,0.334199,0.340497,0.338362,...,0.410350,0.415638,0.410072,0.411254,0.413736,0.406809,0.407430,0.412306,0.418177,0.422698
DZA,Algeria,0.300272,0.301323,0.297807,0.294600,0.298484,0.302522,0.308477,0.314743,0.320064,...,0.284460,0.289123,0.298651,0.321145,0.322282,0.322472,0.325523,0.329650,0.337037,0.345662
AND,Andorra,0.123870,0.126191,0.129692,0.136468,0.141060,0.145479,0.148872,0.150337,0.162162,...,0.281286,0.288686,0.295882,0.299429,0.300399,0.340486,0.348305,0.350802,0.391279,0.452459
AGO,Angola,0.190434,0.190433,0.189082,0.187725,0.188442,0.189209,0.197140,0.205093,0.217805,...,0.216227,0.211618,0.239753,0.242482,0.254117,0.257539,0.260653,0.267595,0.271751,0.272532

In [8]:
readiness.dtypes

Name     object
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012    float64
2013    float64
2014    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
dtype: object

In [9]:
readiness.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, AFG to ZWE
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    192 non-null    object
 1   1995    192 non-null    float64
 2   1996    192 non-null    float64
 3   1997    192 non-null    float64
 4   1998    192 non-null    float64
 5   1999    192 non-null    float64
 6   2000    192 non-null    float64
 7   2001    192 non-null    float64
 8   2002    192 non-null    float64
 9   2003    192 non-null    float64
 10  2004    192 non-null    float64
 11  2005    192 non-null    float64
 12  2006    192 non-null    float64
 13  2007    192 non-null    float64
 14  2008    192 non-null    float64
 15  2009    192 non-null    float64
 16  2010    192 non-null    float64
 17  2011    192 non-null    float64
 18  2012    192 non-null    float64
 19  2013    192 non-null    float64
 20  2014    192 non-null    float64
 21  2015    192 non-null    float64
 22  2016    192 non-null    float64
 23  2017    192 non-null    float64
 24  2018    192 non-null    float64
 25  2019    192 non-null    float64
 26  2020    192 non-null    float64
 27  2021    192 non-null    float64
 28  2022    192 non-null    float64
 29  2023    192 non-null    float64
dtypes: float64(29), object(1)
memory usage: 46.5+ KB

In [10]:
readiness[readiness.iloc[:,2:].mean(axis=1).isnull()]

Empty DataFrame
Columns: [Name, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023]
Index: []

[0 rows x 30 columns]

In [11]:
readiness.describe()

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
count,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,...,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000,192.000000
mean,0.383931,0.384538,0.385624,0.385990,0.387394,0.389539,0.391062,0.393197,0.393840,0.393968,...,0.417264,0.418503,0.421168,0.422489,0.423200,0.424097,0.425423,0.426985,0.428321,0.429514
std,0.106336,0.107231,0.108058,0.108253,0.110196,0.112617,0.113008,0.114911,0.114579,0.116654,...,0.151551,0.151261,0.142917,0.142915,0.141720,0.141276,0.140408,0.140834,0.140460,0.140339
min,0.123870,0.126191,0.129692,0.136468,0.141060,0.145479,0.148872,0.150337,0.162162,0.176725,...,0.114829,0.118849,0.141989,0.139561,0.138402,0.137872,0.132005,0.135361,0.134655,0.132553
25%,0.306530,0.306582,0.306483,0.306059,0.308325,0.308776,0.310342,0.313170,0.311143,0.310211,...,0.294301,0.294924,0.306441,0.309323,0.310920,0.315181,0.321184,0.318318,0.321605,0.321631
50%,0.360566,0.359710,0.362893,0.363823,0.364409,0.364273,0.362583,0.364862,0.365544,0.366292,...,0.391454,0.396094,0.401476,0.400498,0.399084,0.402882,0.406701,0.406400,0.410299,0.418369
75%,0.437153,0.436871,0.436105,0.438399,0.440715,0.442744,0.447757,0.454628,0.454311,0.461531,...,0.502486,0.507171,0.500237,0.502458,0.504720,0.510403,0.517865,0.519094,0.525304,0.524132
max,0.671683,0.673376,0.674756,0.678991,0.684629,0.688954,0.692053,0.696849,0.699825,0.701141,...,0.807202,0.804161,0.785296,0.790234,0.793976,0.795199,0.797507,0.802471,0.801252,0.800124

### READINESS SECTORS - ECONOMIC

In [13]:
economic.shape

(192, 30)

In [14]:
economic.head()

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
AFG,Afghanistan,0.496497,0.496497,0.496497,0.496497,0.496497,0.496497,0.496497,0.496497,0.496497,...,0.201495,0.200231,0.261156,0.238742,0.210240,0.224049,0.213706,0.213706,0.213706,0.213706
ALB,Albania,0.393305,0.393305,0.393305,0.393305,0.393305,0.393305,0.393305,0.393305,0.393305,...,0.366324,0.392592,0.371377,0.376041,0.385143,0.368237,0.362695,0.362695,0.362695,0.362695
DZA,Algeria,0.416625,0.416625,0.416625,0.416625,0.416625,0.416625,0.416625,0.416625,0.416625,...,0.264492,0.269901,0.285383,0.329821,0.324866,0.333213,0.323643,0.323643,0.323643,0.323643
AND,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGO,Angola,0.289057,0.289057,0.289057,0.289057,0.289057,0.289057,0.289057,0.289057,0.289057,...,0.149616,0.139844,0.222872,0.235753,0.239751,0.240090,0.248302,0.248302,0.248302,0.248302

In [15]:
economic.dtypes

Name     object
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012    float64
2013    float64
2014    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
dtype: object

In [16]:
economic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, AFG to ZWE
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    192 non-null    object
 1   1995    185 non-null    float64
 2   1996    185 non-null    float64
 3   1997    185 non-null    float64
 4   1998    185 non-null    float64
 5   1999    185 non-null    float64
 6   2000    185 non-null    float64
 7   2001    185 non-null    float64
 8   2002    185 non-null    float64
 9   2003    185 non-null    float64
 10  2004    185 non-null    float64
 11  2005    185 non-null    float64
 12  2006    185 non-null    float64
 13  2007    185 non-null    float64
 14  2008    185 non-null    float64
 15  2009    185 non-null    float64
 16  2010    185 non-null    float64
 17  2011    185 non-null    float64
 18  2012    185 non-null    float64
 19  2013    185 non-null    float64
 20  2014    185 non-null    float64
 21  2015    185 non-null    float64
 22  2016    185 non-null    float64
 23  2017    185 non-null    float64
 24  2018    185 non-null    float64
 25  2019    185 non-null    float64
 26  2020    185 non-null    float64
 27  2021    185 non-null    float64
 28  2022    185 non-null    float64
 29  2023    185 non-null    float64
dtypes: float64(29), object(1)
memory usage: 46.5+ KB

In [17]:
economic[economic.iloc[:,2:].mean(axis=1).isnull()]

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
AND,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CUB,Cuba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRK,"Korea, Democratic People's Repub",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MCO,Monaco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NRU,Nauru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TKM,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUV,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
economic.describe()

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
count,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,...,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000,185.000000
mean,0.410408,0.410408,0.410408,0.410408,0.410408,0.410408,0.410408,0.410408,0.410408,0.410408,...,0.424320,0.423871,0.428148,0.428436,0.428639,0.427896,0.428115,0.428115,0.428115,0.428115
std,0.061773,0.061773,0.061773,0.061773,0.061773,0.061773,0.061773,0.061773,0.061773,0.061773,...,0.172773,0.171576,0.144886,0.145121,0.144895,0.145839,0.147360,0.147360,0.147360,0.147360
min,0.258338,0.258338,0.258338,0.258338,0.258338,0.258338,0.258338,0.258338,0.258338,0.258338,...,0.013409,0.002138,0.070900,0.065912,0.063678,0.058338,0.052506,0.052506,0.052506,0.052506
25%,0.365223,0.365223,0.365223,0.365223,0.365223,0.365223,0.365223,0.365223,0.365223,0.365223,...,0.299699,0.303489,0.313886,0.313206,0.313076,0.310433,0.310594,0.310594,0.310594,0.310594
50%,0.412836,0.412836,0.412836,0.412836,0.412836,0.412836,0.412836,0.412836,0.412836,0.412836,...,0.414649,0.415232,0.421969,0.421257,0.425208,0.419272,0.416407,0.416407,0.416407,0.416407
75%,0.458602,0.458602,0.458602,0.458602,0.458602,0.458602,0.458602,0.458602,0.458602,0.458602,...,0.515769,0.529049,0.526263,0.524968,0.520854,0.526022,0.533980,0.533980,0.533980,0.533980
max,0.580732,0.580732,0.580732,0.580732,0.580732,0.580732,0.580732,0.580732,0.580732,0.580732,...,0.844522,0.832440,0.786026,0.782107,0.779743,0.774894,0.774250,0.774250,0.774250,0.774250

In [33]:
economic_nan = economic[economic.iloc[:,1:].mean(axis=1).isnull()]
economic_nan_dict = economic_nan['Name'].to_dict()
economic_nan_dict

{'AND': 'Andorra',
 'CUB': 'Cuba',
 'PRK': "Korea, Democratic People's Repub",
 'MCO': 'Monaco',
 'NRU': 'Nauru',
 'TKM': 'Turkmenistan',
 'TUV': 'Tuvalu'}

***TO DO: DECIDE WHAT TO DO ABOUT MISSING VALUES.***

### READINESS SECTORS - GOVERNANCE

In [20]:
governance.shape

(192, 30)

In [21]:
governance.head()

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
AFG,Afghanistan,0.132619,0.132619,0.137714,0.142810,0.138254,0.133699,0.152263,0.170827,0.181367,...,0.193736,0.189167,0.158018,0.148855,0.158038,0.165790,0.141350,0.170461,0.180175,0.185214
ALB,Albania,0.379200,0.379200,0.366713,0.354226,0.356636,0.359045,0.373480,0.387915,0.380313,...,0.487893,0.478459,0.482930,0.481162,0.478875,0.467010,0.465444,0.472364,0.483040,0.491419
DZA,Algeria,0.288133,0.288133,0.277152,0.266172,0.276811,0.287451,0.303095,0.318740,0.332008,...,0.311733,0.309993,0.309649,0.319400,0.321742,0.308001,0.321064,0.323485,0.343917,0.363174
AND,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGO,Angola,0.196202,0.196202,0.192119,0.188036,0.190213,0.192390,0.208023,0.223656,0.250445,...,0.308597,0.304974,0.305727,0.299562,0.329471,0.334141,0.333477,0.352788,0.359633,0.360743

In [22]:
governance.dtypes

Name     object
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012    float64
2013    float64
2014    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
dtype: object

In [23]:
governance.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, AFG to ZWE
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    192 non-null    object
 1   1995    188 non-null    float64
 2   1996    188 non-null    float64
 3   1997    188 non-null    float64
 4   1998    188 non-null    float64
 5   1999    188 non-null    float64
 6   2000    188 non-null    float64
 7   2001    188 non-null    float64
 8   2002    188 non-null    float64
 9   2003    188 non-null    float64
 10  2004    188 non-null    float64
 11  2005    188 non-null    float64
 12  2006    188 non-null    float64
 13  2007    188 non-null    float64
 14  2008    188 non-null    float64
 15  2009    188 non-null    float64
 16  2010    188 non-null    float64
 17  2011    188 non-null    float64
 18  2012    188 non-null    float64
 19  2013    188 non-null    float64
 20  2014    188 non-null    float64
 21  2015    188 non-null    float64
 22  2016    188 non-null    float64
 23  2017    188 non-null    float64
 24  2018    188 non-null    float64
 25  2019    188 non-null    float64
 26  2020    188 non-null    float64
 27  2021    188 non-null    float64
 28  2022    188 non-null    float64
 29  2023    188 non-null    float64
dtypes: float64(29), object(1)
memory usage: 46.5+ KB

In [24]:
governance[governance.iloc[:,2:].mean(axis=1).isnull()]

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
AND,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
COD,"Congo, the Democratic Republic o",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ROU,Romania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TLS,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
governance_nan = governance[governance.iloc[:,1:].mean(axis=1).isnull()]
governance_nan_dict = governance_nan['Name'].to_dict()
governance_nan_dict

{'AND': 'Andorra',
 'COD': 'Congo, the Democratic Republic o',
 'ROU': 'Romania',
 'TLS': 'Timor-Leste'}

***TO DO: DECIDE WHAT TO DO ABOUT MISSING VALUES.***

### READINESS SECTORS - SOCIAL

In [26]:
social.shape

(192, 30)

In [27]:
social.head()

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
AFG,Afghanistan,0.299958,0.299954,0.299952,0.299949,0.299947,0.299946,0.299946,0.299996,0.300355,...,0.340917,0.343624,0.347348,0.350261,0.353833,0.355365,0.355190,0.354151,0.354768,0.355202
ALB,Albania,0.226401,0.227956,0.229920,0.230546,0.231636,0.231957,0.235813,0.240272,0.241466,...,0.376834,0.375864,0.375908,0.376560,0.377190,0.385179,0.394151,0.401858,0.408796,0.413980
DZA,Algeria,0.196058,0.199210,0.199642,0.201003,0.202016,0.203490,0.205711,0.208864,0.211558,...,0.277156,0.287477,0.300922,0.314212,0.320239,0.326203,0.331860,0.341821,0.343552,0.350170
AND,Andorra,0.123870,0.126191,0.129692,0.136468,0.141060,0.145479,0.148872,0.150337,0.162162,...,0.281286,0.288686,0.295882,0.299429,0.300399,0.340486,0.348305,0.350802,0.391279,0.452459
AGO,Angola,0.086044,0.086042,0.086069,0.086083,0.086057,0.086181,0.094340,0.102567,0.113913,...,0.190469,0.190037,0.190661,0.192130,0.193128,0.198386,0.200180,0.201696,0.207319,0.208552

In [28]:
social.dtypes

Name     object
1995    float64
1996    float64
1997    float64
1998    float64
1999    float64
2000    float64
2001    float64
2002    float64
2003    float64
2004    float64
2005    float64
2006    float64
2007    float64
2008    float64
2009    float64
2010    float64
2011    float64
2012    float64
2013    float64
2014    float64
2015    float64
2016    float64
2017    float64
2018    float64
2019    float64
2020    float64
2021    float64
2022    float64
2023    float64
dtype: object

In [29]:
social.info()

<class 'pandas.core.frame.DataFrame'>
Index: 192 entries, AFG to ZWE
Data columns (total 30 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    192 non-null    object
 1   1995    186 non-null    float64
 2   1996    186 non-null    float64
 3   1997    186 non-null    float64
 4   1998    186 non-null    float64
 5   1999    186 non-null    float64
 6   2000    186 non-null    float64
 7   2001    186 non-null    float64
 8   2002    186 non-null    float64
 9   2003    186 non-null    float64
 10  2004    186 non-null    float64
 11  2005    186 non-null    float64
 12  2006    186 non-null    float64
 13  2007    186 non-null    float64
 14  2008    186 non-null    float64
 15  2009    186 non-null    float64
 16  2010    186 non-null    float64
 17  2011    186 non-null    float64
 18  2012    186 non-null    float64
 19  2013    186 non-null    float64
 20  2014    186 non-null    float64
 21  2015    186 non-null    float64
 22  2016    186 non-null    float64
 23  2017    186 non-null    float64
 24  2018    186 non-null    float64
 25  2019    186 non-null    float64
 26  2020    186 non-null    float64
 27  2021    186 non-null    float64
 28  2022    186 non-null    float64
 29  2023    186 non-null    float64
dtypes: float64(29), object(1)
memory usage: 46.5+ KB

In [30]:
social.describe()

,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,...,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000
mean,0.238152,0.239988,0.243237,0.244629,0.249027,0.256193,0.260664,0.266911,0.272129,0.279897,...,0.337422,0.341965,0.345599,0.349203,0.351263,0.353999,0.357544,0.362648,0.366067,0.368136
std,0.124660,0.126797,0.129719,0.131959,0.137043,0.142254,0.144215,0.147088,0.147806,0.151814,...,0.154429,0.154659,0.154283,0.153496,0.149973,0.148483,0.146716,0.147050,0.147389,0.147072
min,0.078527,0.078694,0.081751,0.082735,0.083136,0.083497,0.083825,0.084125,0.084693,0.085041,...,0.116303,0.115668,0.115357,0.120089,0.127031,0.131472,0.133086,0.139537,0.140304,0.141240
25%,0.152981,0.153004,0.153556,0.153135,0.155358,0.157634,0.160106,0.163450,0.170094,0.176506,...,0.230795,0.233956,0.236757,0.239483,0.241009,0.242110,0.251616,0.258837,0.259857,0.262328
50%,0.199906,0.200378,0.202276,0.203330,0.208121,0.213874,0.218867,0.221969,0.227372,0.230151,...,0.287116,0.288915,0.294181,0.298633,0.305604,0.309328,0.314893,0.319156,0.324150,0.325007
75%,0.277552,0.278625,0.287816,0.294691,0.292958,0.299354,0.300512,0.313436,0.329081,0.325356,...,0.427284,0.430786,0.432331,0.436330,0.436614,0.437889,0.441622,0.444542,0.447890,0.451919
max,0.633165,0.635677,0.640140,0.651098,0.657305,0.659572,0.668531,0.683673,0.697635,0.714768,...,0.757788,0.759777,0.761761,0.764137,0.763332,0.764885,0.771470,0.780357,0.787206,0.788338

In [38]:
social[social.iloc[:,2:].mean(axis=1).isnull()]

,Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
ISO3,,,,,,,,,,,,,,,,,,,,,
DMA,Dominica,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
KIR,Kiribati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NRU,Nauru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SLB,Solomon Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SOM,Somalia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TUV,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
social_nan = social[social.iloc[:,21:].mean(axis=1).isnull()]
social_nan_dict = social_nan['Name'].to_dict()
social_nan_dict

{'DMA': 'Dominica',
 'KIR': 'Kiribati',
 'NRU': 'Nauru',
 'SLB': 'Solomon Islands',
 'SOM': 'Somalia',
 'TUV': 'Tuvalu'}

***TO DO: DECIDE WHAT TO DO ABOUT MISSING VALUES***

In [40]:
readiness_null = {
    "economic": economic_nan_dict,
    "governance": governance_nan_dict,
    "social": social_nan_dict
}

In [41]:
readiness_null_df = pd.DataFrame(readiness_null)

In [42]:
readiness_null_df

,economic,governance,social
AND,Andorra,Andorra,NaN
CUB,Cuba,NaN,NaN
PRK,"Korea, Democratic People's Repub",NaN,NaN
MCO,Monaco,NaN,NaN
NRU,Nauru,NaN,Nauru
TKM,Turkmenistan,NaN,NaN
TUV,Tuvalu,NaN,Tuvalu
COD,NaN,"Congo, the Democratic Republic o",NaN
ROU,NaN,Romania,NaN
TLS,NaN,Timor-Leste,NaN
DMA,NaN,NaN,Dominica
KIR,NaN,NaN,Kiribati
SLB,NaN,NaN,Solomon Islands
SOM,NaN,NaN,Somalia

In [43]:
readiness_null_df = readiness_null_df.notna().replace({True:"Missing", False:" "})
readiness_null_df

    economic governance   social
AND  Missing    Missing
CUB  Missing
PRK  Missing
MCO  Missing
NRU  Missing             Missing
TKM  Missing
TUV  Missing             Missing
COD             Missing
ROU             Missing
TLS             Missing
DMA                      Missing
KIR                      Missing
SLB                      Missing
SOM                      Missing

In [46]:
read = readiness_null_df.to_csv("readiness_missing_summary.csv")